id: P003019
initial_creation_type: ocr
source_metadata:
  id: bdr:W20205
  title: གཏེར་ཆེན་བདུད་འཇོམས་ཡབ་སྲས་ཀྱི་རྣམ་ཐར
  author: ''
  volumes:
    280aad4e481740e19bcf55d18fa5609f:
      image_group_id: I1PD38197
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
